sudo: required

os: linux
dist: trusty
jdk: oraclejdk8
language: scala

scala:
  - "2.13.0"
  - "2.12.8"

jdk: openjdk8

matrix:
  include:
    - env: SBT_VERSION=0.13.18
      scala: "2.12.10"
    - env: SBT_VERSION=1.2.8
      scala: "2.12.10"

env:
  - TRAVIS_NODE_VERSION="8.12.0"
  - TRAVIS_NODE_VERSION="10.10.0"

before_install:
  - sudo apt-get update
  # Remove pre-bundled libunwind
  - sudo find /usr -name "*libunwind*" -delete
  # Use pre-bundled clang
  - export PATH=/usr/local/clang-5.0.0/bin:$PATH
  - export CXX=clang++
  # Install Boehm GC and libunwind
  - sudo apt-get install libgc-dev libunwind8-dev
  # Build and install re2 from source
  - git clone https://code.googlesource.com/re2
  - pushd re2
  - git checkout 2017-03-01
  - make -j4 test
  - sudo make install prefix=/usr
  - make testinstall prefix=/usr
  - popd

install:
  - source travis/setNodeVersion.sh

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - source travis/testSbtPlugin.sh
  # Tricks to avoid unnecessary cache updates, from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
